### PR TITLE
Tweaked styles to include box-less headings

### PR DESCRIPTION
**Pull request by nikhilweee**
@gvwilson :
Please add a blockquote `>` and change the class to `heading` while writing your markdown file

    >## Indexing
    {: .heading}

Cheers,
Nikhil

### CODE REVIEW

**Comment by gvwilson** [comment]
Hi Nikhil,

I would like this to work *without* the blockquote - can you resubmit 
with SASS that does that?

Thanks,
Greg

On 2016-03-11 12:37 PM, Nikhil Verma wrote:
>
> @gvwilson <https://github.com/gvwilson> :
> Please add a blockquote |>| and change the class to |heading| while 
> writing your markdown file
>
> |>## Indexing {: .heading} |
>
> Cheers,
> Nikhil
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/gvwilson/python-novice-gapminder/pull/1
>
>
>         Commit Summary
>
>   * tweak scss to include box-less headings
>
>
>         File Changes
>
>   * *M* 10-lists.md
>     <https://github.com/gvwilson/python-novice-gapminder/pull/1/files#diff-0>
>     (8)
>   * *M* _sass/common/_01_typography.scss
>     <https://github.com/gvwilson/python-novice-gapminder/pull/1/files#diff-1>
>     (8)
>
>
>         Patch Links:
>
>   * https://github.com/gvwilson/python-novice-gapminder/pull/1.patch
>   * https://github.com/gvwilson/python-novice-gapminder/pull/1.diff
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gvwilson/python-novice-gapminder/pull/1>.
>

-- 
Dr Greg Wilson
Director of Instructor Training
Software Carpentry Foundation

**Comment by nikhilweee** [comment]
Hi @gvwilson,
For the box to appear around the heading, the heading needs to be wrapped around within an element. This is why the blockquote tag is needed. If you remove the blockquote, you'll have to wrap it around some other tag anyway. That would mean adding raw HTML tags to markdown, which, uh, is ugly!
Also, you just have to add **one** `>` before the `## Heading`, not before every line that follows.
I hope it's fine this way!

**Comment by gvwilson** [comment]
Hi Nikhil,

Hm - we can't put a box and background directly on an h2??

Thanks
Greg

**Comment by nikhilweee** [comment]
I tried doing that, but it didn't work out somehow. Please let me check again!

**Comment by gvwilson** [comment]
Yeah, that's the part I couldn't get to work either - but I feel it 
*should*.

**Comment by nikhilweee** [comment]
@gvwilson : Done!
Please have a look.
Nikhil

**Comment by gvwilson** [comment]
Cool!  But does it need to be `.heading`?  I *think* that `h2.challenge` 
will be unambiguous, won't it?

**Comment by nikhilweee** [comment]
@gvwilson : There you go!

**Comment by gvwilson** [comment]
Excellent!  Can you please adjust the width so that the left edge is aligned with the left edge of the paragraphs?  And can you also please add some vertical space below the h2 to match the vertical space above it?
screen shot 2016-03-11 at 3 36 33 pm

**Comment by nikhilweee** [comment]
@gvwilson : All done! Please have a look

**Comment by gvwilson** [comment]
Excellent - thanks!

**Comment by nikhilweee** [comment]
I'm glad I helped!

**Pull request merged**
